apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rhoai-audio-0717 
  janus-idp.io/tekton: rhoai-audio-0717
  backstage.io/kubernetes-id: rhoai-audio-0717
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rhoai-audio-0717
resources: 
- application-dev.yaml